### ISSUE TITLE
Navigate from home page to case via upcoming events list

### ISSUE THREAD

**Issue by brittberwanger** [codefortulsa/courtbook#51]
![image](https://cloud.githubusercontent.com/assets/4081726/23580543/8b723be6-00c9-11e7-993b-70a2fca2b672.png)

Have the entries in the list on this page navigate to the main page for the case:

![image](https://cloud.githubusercontent.com/assets/4081726/23580563/c05569f0-00c9-11e7-9510-46abf13ddf58.png)

**Comment by ashlux** [comment]
Done in https://github.com/codefortulsa/courtbook/pull/49.
